### ISSUE TITLE
some problems when I want to configure pyang_plugins for swagger editor 

### ISSUE THREAD

**Issue by yali2015** [ict-strauss/COP#7]
Hello arthurMll,
Recently,I am researching the pyang_plugins for swagger editor in the windows7 sysytem not a Linux System. So I want to know whether  the pyang_plugins for swagger editor can be installed in the windows7 system. 
Now I have installed the swagger editor locally and installed the pyang which was downloaded from your github.But I can't find the path like what is  in the README.md ,as follows
Copy the swagger plugin to pyang's plugin directory:

sudo cp pyang_plugins/swagger.py /usr/local/lib/python2.7/dist-packages/{pyang_directory}/plugins/

I can't find the path "pyang_plugins/swagger.py"  ,weather the path is refered to the pyang's install file path .If it is ,But I can't find it in the path.
So is it the problem that I have installed it in the windows7 not a Linux? 
 Can you tell me a detailed install state of the pyang_plugins for swagger editor in the windows7 or in a Linux?

Thank you very much!
I am looking forward to you answer.

```
                                                                                                                    yali 
```

**Comment by arthurMll** [comment]
Hi,

Currently the swagger pyang plugin has been only tested in linux environments. As our swagger plugin doesn't belong to the base pyang distribution, our approach consists on manually install the swagger plugin file directly into the pyang installed files. Namely the instruction you paste in your comment is what we do to include our swagger.py file into the pyang plugins directory : 

e.g. /usr/local/lib/python2.7/dist-packages/{pyang_directory}/plugins/

I am not aware of where is it installed pyang in windows 7 but if you are able to find the directory on which is it installed maybe you can try to paste the swagger.py file inside the /plugins directory as we do in linux. However I don't know if this approach will also work in windows.

Otherwise the best I can tell you is to try it in a Linux distribution and follow the steps of the README.md

Best regards,
Arturo,

**Comment by arthurMll** [comment]
pd: If you succeed to install it on windows I will appreciate if you share with us the steps you did in order to achieve it.

Best.

**Comment by GermanoSMO** [comment]
Hello, I'm actually using the swagger plugin on a python installation on a Windows 7 system.

For Windows7, you have to go to the installation directory for Python, let's suppose it's C:\Python34,
then you have to copy the swagger.py file in this directory:

```
 C:\Python34\Lib\site-packages\pyang\plugins
```

Be careful to navigate in the "Lib" folder and not in the "libs" one (easy to confuse them).
You should replace the "dist-packages" name (used for Linux distribution) with the "site-packages" name (used for Windows7 distribution)

Take also into account that Python 3.x under Windows requires that all python "print" statements have their argument enclosed in quotes (that's not mandatory instead on python under Linux), so in case you manage in having the plugin running but you got some weird error code pointing to a precise line in swagger.py, all you have to do is adding the quoting in the "print" statement, e.g:

```
print hello
```

shall become

```
print "hello"
```

**Comment by arthurMll** [comment]
Hello Germano,

good to know that we are windows compatible too :) 

The issue about the prints is due to python version. In python 3 and beyond the syntax changed. I will update soon the swagger plugin to be fully compatible with python 3.

Best regards,
Arturo.

**Comment by yali2015** [comment]
Hello,GermanoSMO
Thank you very much!,But I can't find the swagger.py ,Is it in the python's install path or pyang's install path or swagger-editor's install path ? And I have found the pyang's plugins int the Python's install file.

Thanks you!

**Comment by arthurMll** [comment]
Hi, 

the swagger.py file is not included in the pyang official distribution nor in the swagger-editor one. 
You can download it in this repository, by cloning the entire COP project.

git clone https://github.com/ict-strauss/COP.git

Once you had download the package you will find the swagger.py file in:  ../COP/pyang_plugins/
, and finally copy it into the directory on which pyang is installed in the windows file system.

Regards,
Arturo.

**Comment by yali2015** [comment]
Hi,arthurMII
Thank you ,I get it. And I will try it later.

Thank you very much!!

**Comment by yali2015** [comment]
Hello,
Now,I am very confused with how to run the swagger editor with pyang_plugins .
The first question is if I must install the swagger-editor locally?
The second question is if I have installed successfully ,how to run it ,run pyang or run swagger-editor?
and what's the meaning of following command? and in the windows7 how I do it?
pyang -f swagger -p yang/yang-cop service-call.yang -o service-call.json

```
  --use the option '-p' to specify the path of the yang models for import purposes.
```

Thank you very much!
