### ISSUE TITLE
some problems when I want to configure pyang_plugins for swagger editor 

### ISSUE THREAD

**Issue by yali2015** [ict-strauss/COP#8]
Hello,
I am so sorry to ask you again.
Now,I am very confused with how to run the swagger editor with pyang_plugins .
The first question is if I must install the swagger-editor locally?
The second question is if I have installed successfully ,how to run it ,run pyang or run swagger-editor?and what's the meaning of following command? and in the windows7 how I do it?

pyang -f swagger -p yang/yang-cop service-call.yang -o service-call.json
  --use the option '-p' to specify the path of the yang models for import purposes.
Thank you very much!

**Comment by GermanoSMO** [comment]
Guess you're somehow mixing things.

Swagger editor and pyang+swagger plugins are to be used in two different steps.
The process to be followed is the following
- start with a valid yang file, e.g. _your_file_.yang
- generate from this yang file a json-structured file suitable for swagger editor, using pyang:
  
  ```
  pyang -f swagger -o <your_file>.swagger <your_file>.yang
  ```
- use the _your_file_.swagger file as input to the swagger editor. You may also use the online swagger editor, not necessary to have a local copy running on your computer.

The -p option is mandatory only if some of the yang files composing your model/interface and imported/included in _your_file_.yang are located in a different folder/directory with respect to the folder where _your_file_.yang is located. If all necessary yang files are in the same folder/directory, you don't need the -p option.

**Comment by yali2015** [comment]
Hello GermanoSMO,
Thank you very much for your special patient!
After reading you answer,my understanding is like following,
for example ,if I want use the swagger editor to make my TapiInformationModel.yang changed into a json file.Only I shoud to do is use following command like you said 

pyang -f  swagger  TapiInformationModel.yang  -o TapiInformationModel.json 

Then I use the swagger-editor online ,import the TapiInformationModel.json,finally I will get what I want .
Is it right?
Thank you !

**Comment by yali2015** [comment]
Hello,
I have successfully import the TapiInformationModel.json into the swagger editor ,and in the right of the page online appear the TapiInformationModel API generated from TapiInformationModel.yang,and  I want to download it like follwing,
File-Download JSON,when I download it and open it ,I found it is not like as in the right of the page online, Is it right that I do or what I should do?

I am looking forward for you answer .
Best Regards.

**Comment by arthurMll** [comment]
Hello,

when you import a swagger model into the online swagger-editor, this service just provide you a visualization of the model you have imported, that is what you see in the right part of the screen. When you download it using the  File-Download JSON option, you will just download the same JSON model that you previously imported.

You can try other services that swagger provides as the swagger-codegen to generate a server-stub implementation from the model or you can try as well the python code-generator that is also uploaded in the COP repository which would provides you a similar server-stub implementation but it python language.

Best,
Arturo.

**Comment by yali2015** [comment]
Hello,
When I delete the file TapiInformationModel.json which was produced through following command
pyang -f swagger TapiInformationModel.yang -o TapiInformationModel.json
Then I use the command again  like follwing 
pyang -f swagger TapiInformationModel.yang -o TapiInformationModel.json
 Then it will produce a file named TapiInformationModel.json.tmp  and its size is 0,so if in this situation,I want a TapiInformationModel.json again ,what should I do ?

Thanks.
I am looking forward for you answer .
Best Regards.

**Comment by GermanoSMO** [comment]
Normally, if you forget to delete in advance the .json file and relaunch the swagger file generation, you get a python error about the impossibility to overwrite an existing file, but the plugin still generates its output with the .json.tmp extension. In this case, all you have to do is delete the old .json and change the extension of the .json.tmp simply into .json.

But, the key point is that the .json.tmp should have a size different than zero. If the size is zero, as in your case, it means that very likely the preliminary pyang validation failed for some reasons, in other words: there may be syntax errors in the Yang source. Alternative, there may be bugs/issues either with the python code or with the swagger plugin processing (both boil in a modification of the python code).

You should then examine the error message produced by the operation for generating the swagger, looking at the very first messages in the output after the command line. In general, whenever you modify or use a new version of a .yang file, the best practice is the following:

1) As a first step, validate the file with a plain pyang processing:

```
 pyang TapiInformationModel.yang
```

and verify that no errors are returned. If pyang complains with errors, you should go to your yang code and fix them.

2) Once the step 1) succeeds, run pyang to produce the swagger file:

```
 pyang -f swagger -o TapiInformationModel.json TapiInformationModel.yang
```

If the yang file is correct, this operation shall succeed. If it doesn't and the plugin returns an error code, it's better to ask for information to investigate about it (if the yang file is valid, the swagger plugin must succeed), taking note of the complete set of error messages returned by the execution of the plugin and reporting it here to allow the developers' investigation.

**Comment by yali2015** [comment]
Hello,
Thank you very much!I have solved all problems because of your help.
you can closed the problem.

Thank you again!
